#!/bin/sh

start () {
	#loglevel=$(uci_get "system.@system[0].cronloglevel")
	[ -d /var/crontabs ] || mkdir -p /var/crontabs
	[ -d /var/crontabs ] && [ ! -f /var/crontabs/root ] && touch /var/crontabs/root
	[ -d /var/spool/cron ] || mkdir -p /var/spool/cron
	ln -s /var/crontabs /var/spool/cron/
	crond -c /etc/crontabs
}

stop() {
	killall -9 crond
}

case "$1" in
	"boot" )
		start
		;;
	"start" )
		start
		;;
	"stop" )
		stop
		;;
	"restart" )
		stop
		start
		;;
	"reload" )
		stop
		start
		;;
esac

