#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

BIN=lighttpd
DEFAULT=/etc/default/$BIN
LOG_D=/var/log/$BIN
RUN_D=/var/run
PID_F=$RUN_D/$BIN.pid
UPLOAD_TMP_D=/tmp/$BIN
UPLOAD_TMP_LOCAL_D=/tmp/${BIN}.local

start() {
	[ -d /tmp/ApplicationData/lighttpd/etc/lighttpd/conf.d ] || mkdir -p /tmp/ApplicationData/lighttpd/etc/lighttpd/conf.d
	/usr/sbin/lighttpd-port init

	[ -f $DEFAULT ] && . $DEFAULT
	mkdir -p $LOG_D
	mkdir -p $RUN_D
	mkdir -p $UPLOAD_TMP_LOCAL_D
	rm -f $UPLOAD_TMP_D
	ln -s $UPLOAD_TMP_LOCAL_D $UPLOAD_TMP_D

	$BIN $OPTIONS
}

stop() {
	killall lighttpd
	/usr/sbin/lighttpd-port off
}


case "$1" in
	"boot" )
		start
		;;
	"start" )
		start
		;;
	"stop" )
		stop
		;;
	"restart" )
		stop
		start
		;;
	"reload" )
		stop
		start
		;;
esac

