#!/bin/sh
# Copyright (C) 2008-2010 OpenWrt.org

#START=50

start() {
	### applying after WAN connection up ###
	exit 0
}

apply() {
	/usr/sbin/nat apply
}

init() {
	exit 0
}

reload() {
	/usr/sbin/nat reload
}

case "$1" in 

	"start" )
		start
		;;
	"apply" )
		apply
		;;
	"init" )
		init
		;;
	"reload" )
		reload
		;;
esac
