#!/bin/sh

start() {
    /usr/sbin/zy_sendfeedback_wrapper 2>&1 > /tmp/sendfeedback.log &
}

stop() {
    if [ -f /var/run/zy_sendfeedback.pid ]; then
        kill -TERM $(cat /var/run/zy_sendfeedback.pid)
        rm /var/run/zy_sendfeedback.pid
    else
        killall zy_sendfeedback_wrapper
    fi
}
restart() {
    stop
    start
}


case "$1" in
    "boot")
        start
    ;;
    "start")
        start
    ;;
    "stop")
        stop
    ;;
    "restart")
        restart
    ;;
    *)
        echo "Usage: $0 [start|stop|restart]"
    ;;
esac
