#!/bin/sh

help()
{
    echo "Zyxel WiFi Assoc monitor control script"
    echo "Usage     WiFiAssocMonitor <Behavior>"
    echo "Behavior: <start> <stop> <restart>"
}

start()
{
    /usr/sbin/wifi_assoc_monitor &
}

stop()
{
    WiFiAssocMonitorPid=$(pidof wifi_assoc_monitor)
    if [ -n "$WiFiAssocMonitorPid" ]; then
        killall wifi_assoc_monitor
    fi
}

restart()
{
    stop
    start
}

case $1 in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    *)
        help
        exit 1
    ;;
esac
exit 0
