#!/bin/sh 
. /sbin/functions.sh
include /sbin

##check mode,if AP/UR,exit
#local sys_mode=$(get_sys_mode)
#[ "$sys_mode" == "2" -o "$sys_mode" == "3" ] && exit 0

sys_mode=`flash get OP_MODE | awk -F'=' '{print $2}'`
[ "$sys_mode" == "1" -o "$sys_mode" == "2" ] && exit 0

vpn_passthrough(){
	pptpenable=$(uci_get nat general pptp)
	l2tpenable=$(uci_get nat general l2tp)
	ipsecenable=$(uci_get nat general ipsec)

	if [ "$pptpenable" == "enable" ];then
	        iptables -D FORWARD -p gre -j DROP 2>/dev/null
			iptables -D FORWARD -p tcp --dport 1723 -j DROP 2>/dev/null
	else
			iptables -D FORWARD -p gre -j DROP 2>/dev/null
			iptables -D FORWARD -p tcp --dport 1723 -j DROP 2>/dev/null
	        iptables -I FORWARD -p tcp --dport 1723 -j DROP
	        iptables -I FORWARD -p gre -j DROP
	fi

	if [ "$l2tpenable" == "enable" ];then
			iptables -D FORWARD -p udp --dport 1701 -j DROP 2>/dev/null
	else
			iptables -D FORWARD -p udp --dport 1701 -j DROP 2>/dev/null
	 		iptables -I FORWARD -p udp --dport 1701 -j DROP
	fi

	if [ "$ipsecenable" == "enable" ];then
			iptables -D FORWARD -p udp --dport 500 -j DROP 2>/dev/null
			iptables -D FORWARD -p udp --dport 4500 -j DROP 2>/dev/null
			iptables -D FORWARD -p udp --dport 51 -j DROP 2>/dev/null
			iptables -D FORWARD -p udp --dport 50 -j DROP 2>/dev/null
	else
			iptables -D FORWARD -p udp --dport 500 -j DROP 2>/dev/null
			iptables -D FORWARD -p udp --dport 4500 -j DROP 2>/dev/null
			iptables -D FORWARD -p udp --dport 51 -j DROP 2>/dev/null
			iptables -D FORWARD -p udp --dport 50 -j DROP 2>/dev/null
	        iptables -I FORWARD -p udp --dport 500 -j DROP
			iptables -I FORWARD -p udp --dport 4500 -j DROP
			iptables -I FORWARD -p udp --dport 51 -j DROP
			iptables -I FORWARD -p udp --dport 50 -j DROP

	fi
}
boot() {

        scan_interfaces

        config_get WAN wan ifname
        config_get LAN lan ifname
        vpn_passthrough


}

apply() {

	## DOS, IP filter, ICMP ping
	#/lib/firewall/configure_firewall
	
	/usr/sbin/configure_firewall

	## iptables app reorder
	#/lib/firewall/iptables_app_order
	
	/usr/sbin/iptables_app_order
	
	 vpn_passthrough

}

EXTRA_HELP="    apply   Apply new rules"
EXTRA_COMMANDS="apply"

cmd=$1

case "$cmd" in
boot) boot
		;;
apply|stop|start|reload|restart|init)
	## firewall
	iptables -F input_rule 2>&- >&-
	iptables -F output_igmp 2>&- >&-
	iptables -F forwarding_rule_filter 2>&- >&-
	iptables -F lan_local_default 2>&- >&-
    
	iptables -D INPUT -j input_rule 2>&- >&-
	iptables -D OUTPUT -j output_igmp 2>&- >&-
	iptables -D FORWARD -j forwarding_rule_filter 2>&- >&-
	iptables -D INPUT -j lan_local_default 2>&- >&-
		    
	iptables -D INPUT -j ACCEPT 2>&- >&-
	iptables -D FORWARD -j ACCEPT 2>&- >&-
     
	iptables -X input_rule 2>&- >&-
	iptables -X output_igmp 2>&- >&-
	iptables -X forwarding_rule_filter 2>&- >&-
	iptables -X lan_local_default 2>&- >&-
    
	## icmp filter
	iptables -F input_icmp 2>&- >&-
	iptables -F forwarding_icmp 2>&- >&-
    
	iptables -D INPUT -p icmp -j input_icmp 2>&- >&-
	iptables -D FORWARD -p icmp -j forwarding_icmp 2>&- >&-
    
	iptables -X input_icmp 2>&- >&-
	iptables -X forwarding_icmp 2>&- >&-
		    
	## ipv4 DoS
	iptables -F DOS_INPUT 2>&- >&-
	iptables -F DOS_FORWARD 2>&- >&-
	iptables -F SYN_FLOODING 2>&- >&-
	iptables -F PORT_SCAN 2>&- >&-
	iptables -F BAD_PING 2>&- >&-
	iptables -t mangle -F DOS_LAND_ATTACK_LOG 2>&- >&-
		
	iptables -D INPUT -j DOS_INPUT 2>/dev/null
	iptables -D FORWARD -j DOS_FORWARD 2>/dev/null
	iptables -t mangle -D PREROUTING -j DOS_LAND_ATTACK_LOG 2>/dev/null
    
	iptables -X DOS_INPUT 2>&- >&-
	iptables -X DOS_FORWARD 2>&- >&-
	iptables -X SYN_FLOODING 2>&- >&-
	iptables -X PORT_SCAN 2>&- >&-
	iptables -X BAD_PING 2>&- >&-
	iptables -t mangle -X DOS_LAND_ATTACK_LOG 2>&- >&-
	
	apply
	;;
esac
