#!/bin/sh

usage(){
	echo "Usage: zyxel_switch_port [lan|wan] [reset]"
}

if [ "$#" -ne 2 ]; then
	usage
	exit 1
fi

case $2 in
	"reset")			
		if [ "$1" == "lan" ]; then
			for i in 1 2 4 8
			do
				echo "$i 0" > /proc/phyPower  #Power OFF
				echo "$i 1" > /proc/phyPower  #Power ON
			done

		fi

		if [ "$1" == "wan" ]; then
			for i in 16
			do
				echo "$i 0" > /proc/phyPower  #Power OFF
				echo "$i 1" > /proc/phyPower  #Power ON
			done
		fi
	;;
        "auto_ipchange")
		if [ "$1" == "lan" ]; then
			for i in 1 2 4 8
			do
				echo "$i 0" > /proc/phyPower  #Power OFF
				echo "$i 1" > /proc/phyPower  #Power ON
			done
		fi
	;;
	*)
		echo "Wrong parameter!!"
	;;
esac
