#!/bin/sh

load_default_old="0"
led_ctrl_old="0"

while :
do
	[ -f "/proc/load_default" ] && {
		load_default=$(cat /proc/load_default)
		if [ "$load_default" != "$load_default_old" ]; then
			if [ "$load_default" == "1" ]; then
				echo "--- [zyxel_btn_monitor]: Reload Default and Reboot ---" > /dev/console
				/sbin/romreset
			elif [ "$load_default" == "3" ]; then
				echo "--- [zyxel_btn_monitor]: Turn on ResetToDefault LED ---" > /dev/console
				zyxel_led_ctrl ResetToDefault
			else
				echo "--- [zyxel_btn_monitor]: /proc/load_default=$load_default ---" > /dev/console
			fi
		fi
		load_default_old="$load_default"
	}

	[ -f "/proc/led_ctrl" ] && {
		led_ctrl=$(cat /proc/led_ctrl)
		if [ "$led_ctrl" != "$led_ctrl_old" ]; then
			if [ "$led_ctrl" == "1" ]; then
				zyxel_led_ctrl BrightnessStepHW
			fi
		fi
		led_ctrl_old="$led_ctrl"
	}

	sleep 0.3
done
